//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.01 at 02:06:16 PM CDT 
//


package cansas1d;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.w3c.dom.Element;


/**
 * <p>Java class for SASentryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SASentryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Run" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;any/>
 *         &lt;element name="SASdata" type="{cansas1d/1.0}SASdataType" maxOccurs="unbounded"/>
 *         &lt;any/>
 *         &lt;element name="SASsample" type="{cansas1d/1.0}SASsampleType"/>
 *         &lt;element name="SASinstrument" type="{cansas1d/1.0}SASinstrumentType"/>
 *         &lt;element name="SASprocess" type="{cansas1d/1.0}SASprocessType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SASnote" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SASentryType", propOrder = {
    "title",
    "run",
    "any",
    "saSdata",
    "saSentryAny2",
    "saSsample",
    "saSinstrument",
    "saSprocess",
    "saSnote"
})
public class SASentryType {

    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "Run", required = true)
    protected List<SASentryType.Run> run;
    @XmlAnyElement
    protected List<Element> any;
    @XmlElement(name = "SASdata", required = true)
    protected List<SASdataType> saSdata;
    @XmlAnyElement
    protected List<Element> saSentryAny2;
    @XmlElement(name = "SASsample", required = true)
    protected SASsampleType saSsample;
    @XmlElement(name = "SASinstrument", required = true)
    protected SASinstrumentType saSinstrument;
    @XmlElement(name = "SASprocess")
    protected List<SASprocessType> saSprocess;
    @XmlElement(name = "SASnote", required = true)
    protected List<Object> saSnote;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the run property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the run property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRun().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SASentryType.Run }
     * 
     * 
     */
    public List<SASentryType.Run> getRun() {
        if (run == null) {
            run = new ArrayList<SASentryType.Run>();
        }
        return this.run;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

    /**
     * Gets the value of the saSdata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saSdata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSASdata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SASdataType }
     * 
     * 
     */
    public List<SASdataType> getSASdata() {
        if (saSdata == null) {
            saSdata = new ArrayList<SASdataType>();
        }
        return this.saSdata;
    }

    /**
     * Gets the value of the saSentryAny2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saSentryAny2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSASentryAny2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getSASentryAny2() {
        if (saSentryAny2 == null) {
            saSentryAny2 = new ArrayList<Element>();
        }
        return this.saSentryAny2;
    }

    /**
     * Gets the value of the saSsample property.
     * 
     * @return
     *     possible object is
     *     {@link SASsampleType }
     *     
     */
    public SASsampleType getSASsample() {
        return saSsample;
    }

    /**
     * Sets the value of the saSsample property.
     * 
     * @param value
     *     allowed object is
     *     {@link SASsampleType }
     *     
     */
    public void setSASsample(SASsampleType value) {
        this.saSsample = value;
    }

    /**
     * Gets the value of the saSinstrument property.
     * 
     * @return
     *     possible object is
     *     {@link SASinstrumentType }
     *     
     */
    public SASinstrumentType getSASinstrument() {
        return saSinstrument;
    }

    /**
     * Sets the value of the saSinstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link SASinstrumentType }
     *     
     */
    public void setSASinstrument(SASinstrumentType value) {
        this.saSinstrument = value;
    }

    /**
     * Gets the value of the saSprocess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saSprocess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSASprocess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SASprocessType }
     * 
     * 
     */
    public List<SASprocessType> getSASprocess() {
        if (saSprocess == null) {
            saSprocess = new ArrayList<SASprocessType>();
        }
        return this.saSprocess;
    }

    /**
     * Gets the value of the saSnote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saSnote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSASnote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getSASnote() {
        if (saSnote == null) {
            saSnote = new ArrayList<Object>();
        }
        return this.saSnote;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Run {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            if (name == null) {
                return "";
            } else {
                return name;
            }
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
