//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.01 at 02:06:16 PM CDT 
//


package net.smallangles.cansas1d;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SASinstrumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SASinstrumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SASsource" type="{cansas1d/1.0}SASsourceType"/>
 *         &lt;element name="SAScollimation" type="{cansas1d/1.0}SAScollimationType" maxOccurs="unbounded"/>
 *         &lt;element name="SASdetector" type="{cansas1d/1.0}SASdetectorType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SASinstrumentType", propOrder = {
    "name",
    "saSsource",
    "saScollimation",
    "saSdetector"
})
public class SASinstrumentType {

    @XmlElement(required = true, defaultValue = "")
    protected String name;
    @XmlElement(name = "SASsource", required = true)
    protected SASsourceType saSsource;
    @XmlElement(name = "SAScollimation", required = true)
    protected List<SAScollimationType> saScollimation;
    @XmlElement(name = "SASdetector", required = true)
    protected List<SASdetectorType> saSdetector;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the saSsource property.
     * 
     * @return
     *     possible object is
     *     {@link SASsourceType }
     *     
     */
    public SASsourceType getSASsource() {
        return saSsource;
    }

    /**
     * Sets the value of the saSsource property.
     * 
     * @param value
     *     allowed object is
     *     {@link SASsourceType }
     *     
     */
    public void setSASsource(SASsourceType value) {
        this.saSsource = value;
    }

    /**
     * Gets the value of the saScollimation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saScollimation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAScollimation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SAScollimationType }
     * 
     * 
     */
    public List<SAScollimationType> getSAScollimation() {
        if (saScollimation == null) {
            saScollimation = new ArrayList<SAScollimationType>();
        }
        return this.saScollimation;
    }

    /**
     * Gets the value of the saSdetector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the saSdetector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSASdetector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SASdetectorType }
     * 
     * 
     */
    public List<SASdetectorType> getSASdetector() {
        if (saSdetector == null) {
            saSdetector = new ArrayList<SASdetectorType>();
        }
        return this.saSdetector;
    }

}
