// Copyright (c) 2013, UChicago Argonne, LLC
// This file is distributed subject to a Software License Agreement found
// in the file LICENSE that is included with this distribution. 

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.27 at 06:30:11 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cansas1d:1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cansas.cansas1d;
